spring:
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553483
    password: 090104
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
          ddl-auto: create


    database-platform: org.hibernate.dialect.OracleDialect